# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='活动名称', max_length=30)),
                ('Region', models.CharField(default='活动地点', max_length=30)),
                ('Content', models.TextField(default='活动内容')),
                ('Date1', models.DateTimeField()),
                ('Date2', models.DateTimeField()),
                ('State', models.CharField(choices=[('0', 'Unconfirmed'), ('1', 'Confirmed'), ('2', 'Denied')], default='0', max_length=1)),
                ('Type', models.CharField(choices=[('0', '普通'), ('1', '义卖'), ('2', '销售'), ('3', '表演')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityParticipantShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttendDateTime', models.DateTimeField(auto_now_add=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='CDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default=None, max_length=30)),
                ('UserObject', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassroomId', models.IntegerField()),
                ('Date1', models.DateTimeField()),
                ('Date2', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(default=None, max_length=30)),
                ('ClubId', models.IntegerField(default=None)),
                ('ShezhangName', models.CharField(default=None, max_length=8)),
                ('ShezhangQq', models.CharField(default=None, max_length=20)),
                ('ShezhangGrade', models.CharField(default=None, max_length=1)),
                ('ShezhangClass', models.CharField(default=None, max_length=2)),
                ('IfRecruit', models.BooleanField()),
                ('EnrollGroupQq', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Label', models.TextField(default='')),
                ('State', models.BooleanField(default=False)),
                ('Stars', models.IntegerField(default=0)),
                ('Introduction', models.TextField(default='')),
                ('Achievements', models.TextField(default='')),
                ('Type', models.CharField(choices=[('1', '自立精神'), ('2', '共生意识'), ('3', '科学态度'), ('4', '人文情怀'), ('5', '领袖气质')], default=None, max_length=10)),
                ('ClubObject', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JoinDateTime', models.DateTimeField(auto_now_add=True)),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=30)),
                ('DateTime', models.DateTimeField()),
                ('Region', models.CharField(default=None, max_length=30)),
                ('Content', models.TextField(default=None)),
                ('ClubObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LostOrFound', models.CharField(default='丢失', max_length=4)),
                ('LinkmanName', models.CharField(default='匿名', max_length=30)),
                ('LinkmanGrade', models.CharField(default='0', max_length=1)),
                ('LinkmanClass', models.CharField(default='0', max_length=2)),
                ('LinkmanPhoneNumber', models.CharField(default='0000000000', max_length=11)),
                ('LinkmanQq', models.CharField(default='0', max_length=20)),
                ('LostObjectName', models.CharField(default='', max_length=100)),
                ('LostPlace', models.CharField(default='', max_length=30)),
                ('Importance', models.BooleanField(default=False)),
                ('Desc', models.TextField(default='')),
                ('LostDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(default='社团', max_length=30)),
                ('LinkmanGrade', models.CharField(default='1', max_length=1)),
                ('LinkmanClass', models.CharField(default='1', max_length=2)),
                ('LinkmanName', models.CharField(default='联系人', max_length=8)),
                ('LinkmanPhoneNumber', models.CharField(default='00000000000', max_length=11)),
                ('LinkmanQq', models.CharField(default='00000000', max_length=20)),
                ('Region', models.CharField(default='00000', max_length=30)),
                ('Date1', models.DateField(default=None)),
                ('Date2', models.TimeField(default=None)),
                ('Process', models.TextField(default='')),
                ('Content', models.TextField(default='')),
                ('Assessment', models.TextField(default='')),
                ('Feeling', models.TextField(default='')),
                ('Stars', models.FloatField(default=0.0)),
                ('StarTime', models.DateTimeField(default=None)),
                ('Pass', models.CharField(default='1', max_length=1)),
                ('CludId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(default=None, max_length=30)),
                ('UserName', models.CharField(default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default=None, max_length=12)),
                ('Class', models.IntegerField()),
                ('Grade', models.IntegerField()),
                ('AttendYear', models.CharField(default=None, max_length=4)),
                ('QQ', models.CharField(default=None, max_length=20)),
                ('Phone', models.CharField(default=None, max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('UserObject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='Member',
            field=models.ManyToManyField(through='jpspapp.ClubMemberShip', to='jpspapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='ClubObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Club'),
        ),
        migrations.AddField(
            model_name='activityparticipantship',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpspapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='ClubObject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jpspapp.Club'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Participants',
            field=models.ManyToManyField(default=None, through='jpspapp.ActivityParticipantShip', to='jpspapp.UserProfile'),
        ),
    ]
