# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpspapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmembership',
            old_name='JoinDateTime',
            new_name='AttendDateTime',
        ),
        migrations.RemoveField(
            model_name='token',
            name='UserName',
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='AttendReason',
            field=models.TextField(default='我想加入啊！'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='State',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='UserObject',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
