# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpspapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('classroom', models.IntegerField()),
                ('attend_year', models.CharField(default='2016', max_length=4)),
                ('club', models.TextField()),
                ('lftlip', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='stars',
        ),
        migrations.RemoveField(
            model_name='club',
            name='proprieter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='club',
            name='achievements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='shezhang_name',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='club',
            name='shezhang_qq',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='read_time',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='Assessment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Date1',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='Date2',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='Feeling',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='LinkmanClass',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='LinkmanGrade',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='LinkmanName',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='LinkmanPhoneNumber',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='post',
            name='LinkmanQq',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='Process',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Region',
            field=models.CharField(default='00000', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='StarTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='Stars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='club',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='label',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('nm', '需要进行社团打分')], max_length=3),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
