# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=30)),
                ('datetime1', models.CharField(default=None, max_length=30)),
                ('datetime2', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(default=None, max_length=30)),
                ('content', models.TextField(default=None)),
            ],
        ),
    ]
