# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0003_auto_20170715_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cevent',
            old_name='username',
            new_name='cusername',
        ),
    ]
