# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0004_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='File',
        ),
        migrations.AddField(
            model_name='file',
            name='FilePath',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
