# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0004_auto_20170715_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevent',
            name='datetime1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cevent',
            name='datetime2',
            field=models.DateTimeField(),
        ),
    ]
