# Generated by Django 2.0.2 on 2018-02-07 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0005_auto_20170819_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='UserObject',
        ),
        migrations.RemoveField(
            model_name='token',
            name='UserObject',
        ),
        migrations.AlterField(
            model_name='activity',
            name='ClubObject',
            field=models.ForeignKey(default=None, on_delete=False, to='jpspapp.Club'),
        ),
        migrations.AlterField(
            model_name='cduser',
            name='UserObject',
            field=models.OneToOneField(default=None, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='ClubObject',
            field=models.ForeignKey(on_delete=False, to='jpspapp.Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='ClubObject',
            field=models.OneToOneField(default=None, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ClubObject',
            field=models.ForeignKey(on_delete=False, to='jpspapp.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='CludId',
            field=models.ForeignKey(default=None, on_delete=False, to='jpspapp.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='UserObject',
            field=models.ForeignKey(default=None, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
