# Generated by Django 2.0.2 on 2018-02-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0006_auto_20180207_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['ClubId']},
        ),
    ]
