# Generated by Django 2.0.2 on 2018-02-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0007_auto_20180208_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='CludId',
            new_name='ClubObject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ClubName',
        ),
    ]
