# Generated by Django 2.0.2 on 2018-02-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0008_auto_20180223_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date1',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Date2',
            new_name='Time',
        ),
    ]
