# Generated by Django 2.0.2 on 2018-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0009_auto_20180223_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='StarTime',
        ),
        migrations.AlterField(
            model_name='post',
            name='Pass',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
