# Generated by Django 2.0.2 on 2018-03-04 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0010_auto_20180223_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserObject',
            field=models.OneToOneField(default=None, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
