# Generated by Django 2.0.2 on 2018-03-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpspapp', '0011_auto_20180304_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ClubObject',
            field=models.OneToOneField(default=None, on_delete=False, to='jpspapp.Club'),
        ),
    ]
